<h3 align="center" style="color:blue">Codebasics Python Course: Numpy Exercise</h3>

Below two numpy arrays are given with following columns. 

* Employee Details (1) Employee ID (2) Department (3) Salary
* Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed

Using these two arrays you need to complete set of tasks which are given in the notebook cells (along with hints)

In [1]:
import numpy as np

# Employee Details (1) Employee ID (2) Department (3) Salary
employee_details = np.array([
    [101, 'Sales', 55000, 'Satya Nadella'],  
    [102, 'HR', 52000, 'Emily Johnson'],    
    [103, 'IT', 72000, 'Fatima Razaak'],        
    [104, 'Sales', 60000, 'John Smith'],    
    [105, 'IT', 68000, 'Priya Singh'],      
    [106, 'HR', 54000, 'Li Wei'],           
    [107, 'IT', 71000, 'Michael Brown'],    
    [108, 'Sales', 59000, 'Sunita Sharma'], 
    [109, 'HR', 53000, 'Chen Wei']          
])

# Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed
performance_metrics = np.array([
    [101, 85, 5],
    [102, 78, 3],
    [103, 92, 7],
    [104, 88, 6],
    [105, 79, 4],
    [106, 81, 5],
    [107, 91, 8],
    [108, 77, 4],
    [109, 83, 4]
])

### Task 1: Merge above two numpy arrays using np.hstack

In [17]:
# write code here
merged_array = np.hstack((employee_details, performance_metrics))
merged_array

array([['101', 'Sales', '55000', 'Satya Nadella', '101', '85', '5'],
       ['102', 'HR', '52000', 'Emily Johnson', '102', '78', '3'],
       ['103', 'IT', '72000', 'Fatima Razaak', '103', '92', '7'],
       ['104', 'Sales', '60000', 'John Smith', '104', '88', '6'],
       ['105', 'IT', '68000', 'Priya Singh', '105', '79', '4'],
       ['106', 'HR', '54000', 'Li Wei', '106', '81', '5'],
       ['107', 'IT', '71000', 'Michael Brown', '107', '91', '8'],
       ['108', 'Sales', '59000', 'Sunita Sharma', '108', '77', '4'],
       ['109', 'HR', '53000', 'Chen Wei', '109', '83', '4']], dtype='<U13')

### Task 2: Print All the Salaries

In [23]:
# write code here
salaries = merged_array[:,2].astype(float)
salaries

array([55000., 52000., 72000., 60000., 68000., 54000., 71000., 59000.,
       53000.])

### Task 3:  Print All the Salaries in Ascending Order

In [29]:
# write code here
sorted_salaries = np.sort(salaries)
sorted_salaries

array([52000., 53000., 54000., 55000., 59000., 60000., 68000., 71000.,
       72000.])

### Task 4:  Iterate through entire array and print only employee id and name

In [37]:
# write code here
print(employee_details[:, 0:2])

[['101' 'Sales']
 ['102' 'HR']
 ['103' 'IT']
 ['104' 'Sales']
 ['105' 'IT']
 ['106' 'HR']
 ['107' 'IT']
 ['108' 'Sales']
 ['109' 'HR']]


### Task 5: Print performance score of all the employees

In [41]:
# write code here
performance_scores = performance_metrics[:,1]
performance_scores

array([85, 78, 92, 88, 79, 81, 91, 77, 83])

### Task 6: Convert these scores to float type by using astype(float) function

In [45]:
# write code here
performance_scores.astype(float)

array([85., 78., 92., 88., 79., 81., 91., 77., 83.])

### Task 7:  Now print the average performance score of all the employees

In [49]:
# write code here
avg = np.average(performance_scores)
avg

83.77777777777777

### Task 8:  Print all the unique departments. You can use np.unique function for this

In [53]:
# first print departments from all the records
departments = employee_details[:, 1]
departments
# write code here

array(['Sales', 'HR', 'IT', 'Sales', 'IT', 'HR', 'IT', 'Sales', 'HR'],
      dtype='<U13')

In [55]:
# now print unique departments
unique_depart = np.unique(departments)
unique_depart
# write code here

array(['HR', 'IT', 'Sales'], dtype='<U13')

### Task 9: Print average salary in HR department

In [63]:
# First print all the records in HR department
hr_depart = employee_details[:,1] == 'HR'
hr_depart
# write code here

array([False,  True, False, False, False,  True, False, False,  True])

In [3]:
# Now from these records only print  the salary column. Convert that to float using astype(float) function

# write code here

In [4]:
# Take an average of this column using np.mean() function

# write code here