In [6]:
import numpy as np

In [10]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [36]:
SIZE = 1000
python_list = list(range(SIZE))

In [38]:
import sys
sys.getsizeof(python_list[0])*len(python_list)

28000

In [40]:
numpy_array = np.arange(SIZE)
numpy_array.nbytes

4000

In [ ]:
#Why?support non homogenous, numpy array in continous memory locations, less time

In [54]:
# Basic Operations
arr1 = np.array([10,11,12])
arr1.ndim

1

In [60]:
arr2 = np.array([[10,11,12],
                 [13,14,15]])
arr2.ndim
arr2[0,1]
arr2.dtype

dtype('int32')

In [62]:
arr2 = np.array([[10,11,12],
                 [13,14,15]], dtype = np.float64)
arr2.dtype

dtype('float64')

In [68]:
arr2.itemsize

8

In [70]:
arr2.size

6

In [72]:
arr2.ndim

2

In [80]:
arr2.shape

(2, 3)

In [82]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])